### ISSUE TITLE
Bug - inaccurate balance/'send' functionality broken for certain genesis accounts

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#46] opened 2022-10-31 04:50 UTC
**Description**
certain genesis account(s) 'Send' functionality is prevented likely due to inaccurate balance

**Additional Details**
- potentially related to https://github.com/telosnetwork/open-block-explorer/issues/388
- possibly resolved by https://github.com/telosnetwork/open-block-explorer/issues/383

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/198933319-a5cfc335-1a39-4337-a17e-84febf1ab76f.png)

**Comment by karynemayer** [comment] 2022-11-29 17:26
@Viterbo could you take a look at this to see if its still happening?

**Comment by Viterbo** [comment] 2022-12-15 16:50
I lost control of my genesis account so I don't have one to test this problem. So I'm marking this issue as blocked until I can solve this other issue #11 about the ability to "view" other account balances. After I complete these I will come back to resume this one.

**Comment by Viterbo** [comment] 2022-12-19 14:38
I finished the necessary changes to be able to log in as this _haytcmjrgige_ genesis account using cleos authenticator but everything worked as expected. I could not reproduce the error.

![image](https://user-images.githubusercontent.com/4420760/208449834-21d2a050-4ec9-4fde-ba41-7ef73a278aa4.png)

**Comment by Kersten-TCD** [comment] 2022-12-19 17:32
@donnyquixotic @Viterbo I have checked balances and send, this seems to be ok now. (REX Bug remains but related to system contracts not updated yet). I am closing this for now.

**Closed by Kersten-TCD** 2022-12-19 17:32 UTC
Labels: 🔬 Needs Grooming, 🐛 Bug
